# Generated by Django 4.0.6 on 2022-08-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description_alter_product_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название для фотографии')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Фотографии')),
            ],
        ),
    ]
