# Generated by Django 4.0.6 on 2022-08-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_aboutusphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusphoto',
            name='image',
            field=models.ImageField(upload_to='shop/', verbose_name='Фотографии'),
        ),
    ]
